app/customers/controllers.py
# Import flask dependencies
from flask import Blueprint, request, render_template, \
                  flash, g, session, redirect, url_for
from flask_login import login_required
# Import password / encryption helper tools
from werkzeug.security import check_password_hash, generate_password_hash

# Import the database object from the main app module
from app import db
from app.customers.forms import SearchCustomer
from app.customers.models import Customer
from app.sec_lib.sec_lib import SecLib

# Define the blueprint: 'auth', set its url prefix: app.url/auth
comm_customers = Blueprint('customers', __name__, url_prefix='/customers')


# Set the route and accepted methods
@comm_customers.route('/', methods=["GET", "POST"])
@login_required
def customers():
    form = SearchCustomer(request.form)
    if form.validate_on_submit():
        # Built in query from SQL Alchemy
        # customers_list = Customer.query.filter_by(name=form.name.data).all()

        # Vulnerable SQL Query
        customers_list = db.engine.execute(f"SELECT * FROM customers WHERE name='{form.name.data}'").all()

        # Safe query using parameters
        # customers_list = db.engine.execute("SELECT * FROM customers WHERE name=?", form.name.data).all()

        # Vulnerable stored XSS code
        if customers_list:
            return render_template("customers/customers.html", customers=customers_list, form=form)

        # Stored XSS safe code
        # if customers_list:
        #     encoded_customers_list = []
        #     for customer in customers_list:
        #         encoded_customer = Customer(
        #                 name=SecLib().prevent_xss_encoding(customer.name),
        #                 contact=SecLib().prevent_xss_encoding(customer.contact),
        #                 phone=SecLib().prevent_xss_encoding(customer.phone)
        #             )
        #         encoded_customer.date_created = customer.date_created
        #         encoded_customer.date_modified = customer.date_modified
        #         encoded_customers_list.append(
        #             encoded_customer
        #         )
        #     return render_template("customers/customers.html", customers=encoded_customers_list, form=form)
        flash(f'Customer {form.name.data} not found', 'error')
    # else:
    #     customers_list = None
    # Prevent stored XSS
    # for customer in customers_list:
    #     customer.name = SecLib().prevent_xss_encoding(customer.name)
    #     customer.phone = SecLib().prevent_xss_encoding(customer.phone)
    #     customer.contact = SecLib().prevent_xss_encoding(customer.contact)
    return render_template("customers/customers.html", customers=None, form=form)

app/index/controllers.py
# Import flask dependencies
from flask import Blueprint, request, render_template, \
                  flash, g, session, redirect, url_for
from flask_login import current_user, login_required

# Import password / encryption helper tools
from werkzeug.security import check_password_hash, generate_password_hash

# Import the database object from the main app module
from app import db, LoginManager

# Define the blueprint: 'auth', set its url prefix: app.url/auth
index = Blueprint('index', __name__)


# Set the route and accepted methods
@index.route('/')
def home():
    return render_template("index/index.html", user=current_user)

app/plans/controllers.py
# Import flask dependencies
from flask import Blueprint, request, render_template, \
                  flash, g, session, redirect, url_for
from flask_login import login_required
# Import password / encryption helper tools
from werkzeug.security import check_password_hash, generate_password_hash

# Import the database object from the main app module
from app import db

# Define the blueprint: 'auth', set its url prefix: app.url/auth
comm_plans = Blueprint('plans', __name__, url_prefix='/plans')


# Set the route and accepted methods
@comm_plans.route('/')
@login_required
def plans():
    return render_template("plans/plans.html")

app/sectors/controllers.py
# Import flask dependencies
from flask import Blueprint, request, render_template, \
                  flash, g, session, redirect, url_for
from flask_login import login_required
# Import password / encryption helper tools
from werkzeug.security import check_password_hash, generate_password_hash

# Import the database object from the main app module
from app import db

# Define the blueprint: 'auth', set its url prefix: app.url/auth
comm_sectors = Blueprint('sectors', __name__, url_prefix='/sectors')


# Set the route and accepted methods
@comm_sectors.route('/')
@login_required
def sectors():
    return render_template("sectors/sectors.html")

app/templates/main_template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% block head %} {% endblock %}
    <title>{% block title %} {% endblock %} - Communication LTD </title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="{{ url_for('index.home') }}"><i class="bi bi-wifi"></i> Communication LTD</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown"
                aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('auth.signin') }}"><i class="bi bi-box-arrow-in-right"></i>
                        Sign In</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('auth.signup') }}"><i class="bi bi-input-cursor-text"></i> Sign
                        Up</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('auth.change_password') }}"><i class="bi bi-arrow-repeat"></i>
                        Change Password</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('admin_page.manager') }}"><i class="bi bi-briefcase"></i> Admin</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('customers.customers') }}"><i
                            class="bi bi-person-lines-fill"></i> Customers</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('plans.plans') }}"><i class="bi bi-bookmark-star"></i>
                        Plans</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('sectors.sectors') }}"><i class="bi bi-box"></i> Sectors</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('auth.signout') }}"><i class="bi bi-box-arrow-right"></i> Sign
                        Out</a>
                </li>
            </ul>
            {% if user %}
            <span class="text-right navbar-text">
                &#9;&#9;&#9;<i class="bi bi-person"></i> {{ user.name }}
            </span>
            {% endif %}
        </div>
    </div>
</nav>
<br/>
<div class="container">
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    <div>
        {% for category, message in messages %}
        <div class="alert alert-primary alert-dismissible fade show" role="alert">
            <strong>{{ category }}</strong> {{ message }}
        </div>
        {% endfor %}
    </div>
    {% endif %}
    {% endwith %}
    {% block content %} {% endblock %}
</div>
<div>
    {% block footer %} {% endblock %}
</div>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet"
      integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">
{% block endjs %} {% endblock %}
</body>
</html>